/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Frame;
import javax.swing.JPanel;
import paneles.menu.EmptyMenuPanel;
import paneles.menu.MenuPanel;
import user.User;

/**
 *
 * @author sofia
 */
public class AppUserLists extends javax.swing.JFrame {

    /**
     * Creates new form AppUserLists
     */
    public AppUserLists(User user) 
    {
        menuOn = false;
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);//para que la ventana inicie en el centro de la pantalla
        
        //creo los paneles
        homescreenApp = new PantallaPrincipalApp(this.user);
        
        //creo un panel Menu cerrado
        closedMenu = new EmptyMenuPanel();
        closedMenu.setSize(5, 5);
        
        //creo un panel menu
        menu = new MenuPanel(); 
        menu.setSize(203, 187);
        
        //confirmo el tamaño del contenedor en los paneles
        homescreenApp.setSize(700, 450);
        
        //posicion con respecto al contenedor
        homescreenApp.setLocation(0, 0);
        
        //cargo al principio la pantalla de LogIn
        contentScreen(homescreenApp,contentScreenApp); 
        
        //menu
        contentMenu.setVisible(false);
        contentMenu.setLocation(0, 0);
        contentScreen(closedMenu,contentMenu);
    }
    
    public void contentScreen(Component panel, JPanel panelContent)
    {
        panelContent.removeAll();
        panelContent.add(panel,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        ButtonMenu = new javax.swing.JButton();
        contentMenu = new javax.swing.JPanel();
        barraArriba = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JButton();
        botonMinimizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contentScreenApp = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu/botonMenu.png"))); // NOI18N
        ButtonMenu.setBorderPainted(false);
        ButtonMenu.setContentAreaFilled(false);
        ButtonMenu.setMaximumSize(new java.awt.Dimension(25, 25));
        ButtonMenu.setMinimumSize(new java.awt.Dimension(25, 25));
        ButtonMenu.setPreferredSize(new java.awt.Dimension(25, 25));
        ButtonMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu/botonMenuMouseOver.png"))); // NOI18N
        ButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        contentMenu.setBackground(new java.awt.Color(204, 204, 255));
        contentMenu.setMaximumSize(new java.awt.Dimension(203, 162));
        contentMenu.setMinimumSize(new java.awt.Dimension(5, 5));
        contentMenu.setPreferredSize(new java.awt.Dimension(203, 162));

        javax.swing.GroupLayout contentMenuLayout = new javax.swing.GroupLayout(contentMenu);
        contentMenu.setLayout(contentMenuLayout);
        contentMenuLayout.setHorizontalGroup(
            contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        contentMenuLayout.setVerticalGroup(
            contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(contentMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, 160));

        barraArriba.setBackground(new java.awt.Color(195, 225, 203));
        barraArriba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCerrar.png"))); // NOI18N
        botonCerrar.setBorderPainted(false);
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setMaximumSize(new java.awt.Dimension(16, 16));
        botonCerrar.setMinimumSize(new java.awt.Dimension(16, 16));
        botonCerrar.setPreferredSize(new java.awt.Dimension(16, 16));
        botonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCerrarMouseOver.png"))); // NOI18N
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        barraArriba.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMinimizar.png"))); // NOI18N
        botonMinimizar.setBorderPainted(false);
        botonMinimizar.setContentAreaFilled(false);
        botonMinimizar.setMaximumSize(new java.awt.Dimension(16, 16));
        botonMinimizar.setMinimumSize(new java.awt.Dimension(16, 16));
        botonMinimizar.setPreferredSize(new java.awt.Dimension(16, 16));
        botonMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMinimizarMouseOver.png"))); // NOI18N
        botonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMinimizarActionPerformed(evt);
            }
        });
        barraArriba.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taskMasterProTitulo.png"))); // NOI18N
        barraArriba.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        getContentPane().add(barraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        contentScreenApp.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout contentScreenAppLayout = new javax.swing.GroupLayout(contentScreenApp);
        contentScreenApp.setLayout(contentScreenAppLayout);
        contentScreenAppLayout.setHorizontalGroup(
            contentScreenAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        contentScreenAppLayout.setVerticalGroup(
            contentScreenAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(contentScreenApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMinimizarActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void ButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuActionPerformed
        //si el boton esta encendido se tiene que apagar
        if(menuOn)
        {
            //cierro el menu
            contentScreen(closedMenu,contentMenu);
            contentMenu.setVisible(false);
            menuOn = false;//se cierra
        }
        else
        {
            //abro el menu
            contentMenu.setVisible(true);
            contentMenu.setSize(203, 162);
            contentScreen(menu,contentMenu);
            menuOn = true;//se abre
        }
    }//GEN-LAST:event_ButtonMenuActionPerformed

    public static void menuContentScreenApp()
    {
        
    }
    
    public static User user;
    public static PantallaPrincipalApp homescreenApp;
    public static AppUserLists app;
    public static boolean menuOn;//si el menu esta abierto
    public static EmptyMenuPanel closedMenu;
    public static MenuPanel menu;
    /**
     * @param args the command line arguments
     */    
    public static void main(String args[]) 
    {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUserLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUserLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUserLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUserLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                app = new AppUserLists(user);
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMenu;
    private javax.swing.JPanel barraArriba;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonMinimizar;
    private javax.swing.JPanel contentMenu;
    private javax.swing.JPanel contentScreenApp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
