/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import static paneles.PantallaInicial.sistemaUsuarios;
import user.exceptions.IncorrectPasswordException;
import user.exceptions.UserNotFoundException;

/**
 *
 * @author sofia
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_email = new javax.swing.JTextField();
        text_password = new javax.swing.JPasswordField();
        infoUsuarioEmail = new javax.swing.JLabel();
        imagenFondoEmail = new javax.swing.JLabel();
        infoUsuarioPassword = new javax.swing.JLabel();
        imagenFondoContraseña = new javax.swing.JLabel();
        ButtonLogin = new javax.swing.JButton();
        errorText_login = new javax.swing.JLabel();
        errorText_email = new javax.swing.JLabel();
        errorText_password = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 128, 97));
        setMaximumSize(new java.awt.Dimension(700, 307));
        setMinimumSize(new java.awt.Dimension(700, 307));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_email.setBackground(new java.awt.Color(195, 225, 203));
        text_email.setForeground(new java.awt.Color(102, 102, 102));
        text_email.setBorder(null);
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });
        add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 350, 30));

        text_password.setBackground(new java.awt.Color(195, 225, 203));
        text_password.setForeground(new java.awt.Color(102, 102, 102));
        text_password.setBorder(null);
        add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 350, 30));

        infoUsuarioEmail.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioEmail.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioEmail.setText("Email");
        add(infoUsuarioEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        imagenFondoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        imagenFondoEmail.setMaximumSize(new java.awt.Dimension(370, 30));
        imagenFondoEmail.setMinimumSize(new java.awt.Dimension(370, 30));
        imagenFondoEmail.setPreferredSize(new java.awt.Dimension(370, 30));
        add(imagenFondoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        infoUsuarioPassword.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioPassword.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword.setText("Contraseña");
        add(infoUsuarioPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        imagenFondoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        ButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/LogIn.png"))); // NOI18N
        ButtonLogin.setBorderPainted(false);
        ButtonLogin.setContentAreaFilled(false);
        ButtonLogin.setMaximumSize(new java.awt.Dimension(110, 40));
        ButtonLogin.setMinimumSize(new java.awt.Dimension(110, 40));
        ButtonLogin.setPreferredSize(new java.awt.Dimension(110, 40));
        ButtonLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/LogInMouseOver.png"))); // NOI18N
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        errorText_login.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_login.setForeground(new java.awt.Color(255, 153, 153));
        errorText_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorText_login.setAutoscrolls(true);
        errorText_login.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 310, 20));

        errorText_email.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_email.setForeground(new java.awt.Color(255, 153, 153));
        errorText_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_email.setAutoscrolls(true);
        errorText_email.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, 20));

        errorText_password.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_password.setForeground(new java.awt.Color(255, 153, 153));
        errorText_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_password.setAutoscrolls(true);
        errorText_password.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 140, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_text_emailActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // Se loguea un usuario
        //verificar que el usuario existe
        try
        {
            String email = text_email.getText();
            String password = text_password.getText();
            errorText_email.setText("");
            errorText_password.setText("");
            errorText_login.setText("");
            
            
            if(email.isEmpty())
            {
                errorText_email.setText("Ingrese un email");                
            }
            else if(password.isEmpty())
            {
                errorText_password.setText("Ingrese una contraseña");  
            }
            else
            {
                sistemaUsuarios.login(email, password);
            }
        }
        catch(UserNotFoundException ex)
        {
            errorText_login.setText(ex.getMessage());
        }
        catch(IncorrectPasswordException ex)
        {
            errorText_login.setText(ex.getMessage());
        }
    }//GEN-LAST:event_ButtonLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JLabel errorText_email;
    private javax.swing.JLabel errorText_login;
    private javax.swing.JLabel errorText_password;
    private javax.swing.JLabel imagenFondoContraseña;
    private javax.swing.JLabel imagenFondoEmail;
    private javax.swing.JLabel infoUsuarioEmail;
    private javax.swing.JLabel infoUsuarioPassword;
    private javax.swing.JTextField text_email;
    private javax.swing.JPasswordField text_password;
    // End of variables declaration//GEN-END:variables
}
