/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import APIController.APIController;
import fileController.FileController;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.net.MalformedURLException;
import location.Exceptions.EmptyLocationException;
import org.json.JSONException;
import paneles.ListasPaneles.TaskListCalendarPanel;
import paneles.ListasPaneles.TaskListPanel;
import paneles.ListasPaneles.TaskListTrackPanel;
import static paneles.PantallaInicial.app;
import paneles.weather.LocationWeatherPanel;
import paneles.weather.NoLocationWeatherPanel;
import user.User;
import userLists.UserLists;
import weather.Weather;

/**
 * INGRESAR API KEY
 * @author sofia
 */
public class PantallaPrincipalApp extends javax.swing.JPanel {
    private String APIKEY;
    public static NoLocationWeatherPanel noLocationPanel;
    public static LocationWeatherPanel weatherPanel;
    public static User user;
    private UserLists userLists;
    /**
     * Creates new form PantallaPrincipalApp
     */
    public PantallaPrincipalApp(User user, UserLists userLists) {
        this.userLists = userLists;
        this.user = user;
        APIKEY = FileController.readAPIKeyInFile();
        
        initComponents();
        
        noApyKeyPanel.setVisible(false);
        updateWeather();
        
    }
    
    public void updateWeather()
    {
        
        if(!user.getLocation().isEmpty() && !APIKEY.isEmpty())
        {
            //si tiene una localizacion muestro el clima
            //si no tiene algun problema para extraer el clima entra a el otro panel
            try
            {
                //creo el Clima
                Weather weather = new Weather();
                
                //actualizo el clima
                weather.updateWeather(user.getLocation(), APIKEY);
                
                //creo el panel
                weatherPanel = new LocationWeatherPanel(weather);
            
                //confirmo el tamaño del contenedor en el panel
                weatherPanel.setSize(661, 170);
            
                //posicion con respecto al contenedor
                weatherPanel.setLocation(0, 0);
            
                //muestro el panel en el contenedor
                contentWeather(weatherPanel);
            } 
            catch (JSONException ex) 
            {
                weatherPanelnoLocation();
            } 
            catch (IOException ex) 
            {
                weatherPanelnoLocation();
            }
            catch (EmptyLocationException ex) 
            {
                weatherPanelnoLocation();
            }
        }
        else
        {            
            //si no tiene cargada una localizacion muestro un panel de info
            
            weatherPanelnoLocation();
            
            
        }
        
        if(APIKEY.isEmpty())
        {
            //muestro pantalla para ingresar apikey
            noApyKeyPanel.setVisible(true);
        }
        else
        {
            noApyKeyPanel.setVisible(false);
        }
    }
    
    private void weatherPanelnoLocation()
    {        
        //creo el panel
        noLocationPanel = new NoLocationWeatherPanel();
        
        //confirmo el tamaño del contenedor en el panel
        noLocationPanel.setSize(661, 170);
            
        //posicion con respecto al contenedor
        noLocationPanel.setLocation(0, 0);
            
        //muestro el panel en el contenedor
        contentWeather(noLocationPanel);
        
    }

    public void contentWeather(Component panel)
    {
        contentWeather.removeAll();
        contentWeather.add(panel,BorderLayout.CENTER);
        contentWeather.revalidate();
        contentWeather.repaint();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noApyKeyPanel = new javax.swing.JPanel();
        text_errorFaltaApyKey = new javax.swing.JLabel();
        text_apyKey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        apyKeyInvalida = new javax.swing.JLabel();
        contentWeather = new javax.swing.JPanel();
        buttonTaskList = new javax.swing.JButton();
        buttonCalendarList = new javax.swing.JButton();
        buttonTrakingList = new javax.swing.JButton();

        setBackground(new java.awt.Color(195, 225, 203));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noApyKeyPanel.setBackground(new java.awt.Color(195, 225, 203));
        noApyKeyPanel.setOpaque(false);
        noApyKeyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_errorFaltaApyKey.setForeground(new java.awt.Color(255, 51, 51));
        text_errorFaltaApyKey.setText("Falta ApyKey");
        noApyKeyPanel.add(text_errorFaltaApyKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 80, 30));

        text_apyKey.setBackground(new java.awt.Color(227, 246, 246));
        text_apyKey.setForeground(new java.awt.Color(204, 204, 204));
        text_apyKey.setText("Ingresar ApiKey");
        text_apyKey.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        noApyKeyPanel.add(text_apyKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 160, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 153));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        noApyKeyPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 30));

        apyKeyInvalida.setForeground(new java.awt.Color(255, 51, 51));
        noApyKeyPanel.add(apyKeyInvalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 280, 30));

        add(noApyKeyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 660, 70));

        contentWeather.setBackground(new java.awt.Color(255, 204, 204));
        contentWeather.setMaximumSize(new java.awt.Dimension(660, 170));
        contentWeather.setMinimumSize(new java.awt.Dimension(660, 170));
        contentWeather.setPreferredSize(new java.awt.Dimension(660, 170));

        javax.swing.GroupLayout contentWeatherLayout = new javax.swing.GroupLayout(contentWeather);
        contentWeather.setLayout(contentWeatherLayout);
        contentWeatherLayout.setHorizontalGroup(
            contentWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        contentWeatherLayout.setVerticalGroup(
            contentWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        add(contentWeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        buttonTaskList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonTaskList.png"))); // NOI18N
        buttonTaskList.setBorderPainted(false);
        buttonTaskList.setContentAreaFilled(false);
        buttonTaskList.setMaximumSize(new java.awt.Dimension(661, 55));
        buttonTaskList.setMinimumSize(new java.awt.Dimension(661, 55));
        buttonTaskList.setPreferredSize(new java.awt.Dimension(661, 55));
        buttonTaskList.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonTaskListMouseOver.png"))); // NOI18N
        buttonTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTaskListActionPerformed(evt);
            }
        });
        add(buttonTaskList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        buttonCalendarList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonListaCalendario.png"))); // NOI18N
        buttonCalendarList.setBorderPainted(false);
        buttonCalendarList.setContentAreaFilled(false);
        buttonCalendarList.setMaximumSize(new java.awt.Dimension(661, 55));
        buttonCalendarList.setMinimumSize(new java.awt.Dimension(661, 55));
        buttonCalendarList.setPreferredSize(new java.awt.Dimension(661, 55));
        buttonCalendarList.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonListaCalendarioMouseOver.png"))); // NOI18N
        buttonCalendarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalendarListActionPerformed(evt);
            }
        });
        add(buttonCalendarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        buttonTrakingList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonListaTraqueo.png"))); // NOI18N
        buttonTrakingList.setBorderPainted(false);
        buttonTrakingList.setContentAreaFilled(false);
        buttonTrakingList.setMaximumSize(new java.awt.Dimension(661, 55));
        buttonTrakingList.setMinimumSize(new java.awt.Dimension(661, 55));
        buttonTrakingList.setPreferredSize(new java.awt.Dimension(661, 55));
        buttonTrakingList.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonListaTraqueoMouseOver.png"))); // NOI18N
        buttonTrakingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrakingListActionPerformed(evt);
            }
        });
        add(buttonTrakingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalendarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalendarListActionPerformed
        //reemplazo la pantalla principal con la lista de tareas
        app.replaceScreen(new TaskListCalendarPanel(userLists));
    }//GEN-LAST:event_buttonCalendarListActionPerformed

    private void buttonTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTaskListActionPerformed
        //reemplazo la pantalla principal con la lista de tareas con calendario
        app.replaceScreen(new TaskListPanel(userLists));
    }//GEN-LAST:event_buttonTaskListActionPerformed

    private void buttonTrakingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrakingListActionPerformed
        //reemplazo la pantalla principal con la lista de tareas con traqueo
        app.replaceScreen(new TaskListTrackPanel(userLists));
    }//GEN-LAST:event_buttonTrakingListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String prueba = "https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid="+text_apyKey.getText();
        
        try
        {
            //intento hacer una llamada con esa api
            APIController.getInfo(prueba);
            
            APIKEY = text_apyKey.getText();
            
            //guardo la apiKEY en un archivo
            FileController.saveAPIKeyInFile(APIKEY);
            updateWeather();
            noApyKeyPanel.setVisible(false);           
        }
        catch(MalformedURLException ex)
        {
            
        } 
        catch (IOException ex) 
        {
            
        }
        catch(RuntimeException ex)
        {
            apyKeyInvalida.setText("API key invalida");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apyKeyInvalida;
    private javax.swing.JButton buttonCalendarList;
    private javax.swing.JButton buttonTaskList;
    private javax.swing.JButton buttonTrakingList;
    private javax.swing.JPanel contentWeather;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel noApyKeyPanel;
    private javax.swing.JTextField text_apyKey;
    private javax.swing.JLabel text_errorFaltaApyKey;
    // End of variables declaration//GEN-END:variables
}
