/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import fileController.FileController;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import static paneles.LoginPanel.seePassword;
import static paneles.LoginPanel.seePasswordButton;
import static paneles.PantallaInicial.sistemaUsuarios;
import user.User;
import user.UsersSystem;
import user.exceptions.EmptyEmailException;
import user.exceptions.EmptyPasswordException;
import user.exceptions.IncorrectPasswordException;
import user.exceptions.InvalidEmailException;
import user.exceptions.InvalidPasswordException;
import user.exceptions.UserAlreadyExistException;
import user.exceptions.UserNotFoundException;
import visualElements.ButtonImage;
import visualElements.VisualSeePassword;

/**
 *
 * @author sofia
 */
public class SignupPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form panelSignup
     */
    public static boolean seePassword1;//booleando que determina si se va la contraseña
    public static boolean seePassword2;
    public static VisualSeePassword seePasswordButton1;
    public static VisualSeePassword seePasswordButton2;
    
    /**
     * SignupPanel
     */
    public SignupPanel() 
    {
        seePasswordButton1 = new VisualSeePassword();
        seePasswordButton2 = new VisualSeePassword();
        
        seePassword1 = false;
        seePassword2 = false;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_password = new javax.swing.JPasswordField();
        infoUsuarioEmail = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        imagenFondoEmail = new javax.swing.JLabel();
        infoUsuarioPassword = new javax.swing.JLabel();
        imagenFondoContraseña = new javax.swing.JLabel();
        ButtonSignup = new javax.swing.JButton();
        text_passwordConfirmed = new javax.swing.JPasswordField();
        imagenFondoContraseña2 = new javax.swing.JLabel();
        infoUsuarioPassword2 = new javax.swing.JLabel();
        errorText_email = new javax.swing.JLabel();
        errorText_password = new javax.swing.JLabel();
        errorText_password2 = new javax.swing.JLabel();
        errorText_signup = new javax.swing.JLabel();
        userSavedText = new javax.swing.JLabel();
        buttonSeePassword = new javax.swing.JButton();
        buttonSeePassword2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 128, 97));
        setMaximumSize(new java.awt.Dimension(700, 307));
        setMinimumSize(new java.awt.Dimension(700, 307));
        setPreferredSize(new java.awt.Dimension(700, 307));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_password.setBackground(new java.awt.Color(195, 225, 203));
        text_password.setForeground(new java.awt.Color(102, 102, 102));
        text_password.setBorder(null);
        add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 350, 30));

        infoUsuarioEmail.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioEmail.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioEmail.setText("Email");
        add(infoUsuarioEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        text_email.setBackground(new java.awt.Color(195, 225, 203));
        text_email.setForeground(new java.awt.Color(102, 102, 102));
        text_email.setBorder(null);
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });
        add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 350, 30));

        imagenFondoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        infoUsuarioPassword.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioPassword.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword.setText("Contraseña");
        add(infoUsuarioPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        imagenFondoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        ButtonSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/Signup.png"))); // NOI18N
        ButtonSignup.setBorderPainted(false);
        ButtonSignup.setContentAreaFilled(false);
        ButtonSignup.setMaximumSize(new java.awt.Dimension(110, 40));
        ButtonSignup.setMinimumSize(new java.awt.Dimension(110, 40));
        ButtonSignup.setPreferredSize(new java.awt.Dimension(110, 40));
        ButtonSignup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/SignupMouseOver.png"))); // NOI18N
        ButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignupActionPerformed(evt);
            }
        });
        add(ButtonSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        text_passwordConfirmed.setBackground(new java.awt.Color(195, 225, 203));
        text_passwordConfirmed.setForeground(new java.awt.Color(102, 102, 102));
        text_passwordConfirmed.setBorder(null);
        add(text_passwordConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 350, 30));

        imagenFondoContraseña2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        infoUsuarioPassword2.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioPassword2.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword2.setText("Confirme su contraseña");
        add(infoUsuarioPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        errorText_email.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_email.setForeground(new java.awt.Color(255, 153, 153));
        errorText_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_email.setAutoscrolls(true);
        errorText_email.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 370, 20));

        errorText_password.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_password.setForeground(new java.awt.Color(255, 153, 153));
        errorText_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_password.setAutoscrolls(true);
        errorText_password.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 370, 20));

        errorText_password2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_password2.setForeground(new java.awt.Color(255, 153, 153));
        errorText_password2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_password2.setAutoscrolls(true);
        errorText_password2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 370, 20));

        errorText_signup.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_signup.setForeground(new java.awt.Color(255, 153, 153));
        errorText_signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorText_signup.setAutoscrolls(true);
        errorText_signup.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 250, 20));

        userSavedText.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        userSavedText.setForeground(new java.awt.Color(0, 204, 0));
        userSavedText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userSavedText.setAutoscrolls(true);
        userSavedText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(userSavedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 250, 20));

        buttonSeePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/dontSeePasswordButton.png"))); // NOI18N
        buttonSeePassword.setBorderPainted(false);
        buttonSeePassword.setContentAreaFilled(false);
        buttonSeePassword.setMaximumSize(new java.awt.Dimension(30, 30));
        buttonSeePassword.setMinimumSize(new java.awt.Dimension(30, 30));
        buttonSeePassword.setPreferredSize(new java.awt.Dimension(30, 30));
        buttonSeePassword.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/seePasswordButton.png"))); // NOI18N
        buttonSeePassword.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/dontSeePasswordButtonMouseOver.png"))); // NOI18N
        buttonSeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeePasswordActionPerformed(evt);
            }
        });
        add(buttonSeePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        buttonSeePassword2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/dontSeePasswordButton.png"))); // NOI18N
        buttonSeePassword2.setBorderPainted(false);
        buttonSeePassword2.setContentAreaFilled(false);
        buttonSeePassword2.setMaximumSize(new java.awt.Dimension(30, 30));
        buttonSeePassword2.setMinimumSize(new java.awt.Dimension(30, 30));
        buttonSeePassword2.setPreferredSize(new java.awt.Dimension(30, 30));
        buttonSeePassword2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/seePasswordButton.png"))); // NOI18N
        buttonSeePassword2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/dontSeePasswordButtonMouseOver.png"))); // NOI18N
        buttonSeePassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeePassword2ActionPerformed(evt);
            }
        });
        add(buttonSeePassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ButtonSignupActionPerformed
     * @param evt 
     */
    private void ButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignupActionPerformed
        //vacio los textos de error
        errorText_email.setText("");
        errorText_password.setText("");
        errorText_password2.setText("");
        errorText_signup.setText("");
        
        // Se inscribe un nuevo usuario
        //verificar que el mail es valido
        try
        {
            boolean validEmail = User.validEmail(text_email.getText());
            boolean validPassword = User.validPassword(text_password.getText());
            if(validEmail && validPassword)
            {
                //verifico antes que la segunda contraseña y la primera coincidan
                if(text_password.getText().contentEquals(text_passwordConfirmed.getText()))
                {
                    User user = new User(text_email.getText(),text_password.getText());;
                    String saved;
                    
                    //veo si el usuario existe en el archivo de usuarios eliminados
                    try 
                    {
                        sistemaUsuarios.readDeletedUsersInFile();
                        user = sistemaUsuarios.searchDeletedUser(text_email.getText());
                        sistemaUsuarios.deleteUserDeleted(user);
                    } 
                    catch (IOException ex) 
                    {
                        System.out.println("exception 1");
                    } 
                    catch (UserNotFoundException ex) 
                    {
                        System.out.println("exception 2");
                    } 

                    //agrego el usuario a el sistema
                    sistemaUsuarios.signup(user);
                    
                    //guardo la lista de usuarios en el archivo
                    saved = sistemaUsuarios.saveUsersInFile();
                    
                    //si no se guardo correctamente informo el error al usuario
                    if(saved.contains("ERROR"))
                    {
                        errorText_signup.setText(saved);
                    }
                    else
                    {
                        //mensaje verde el usuario se guardo correctamente
                        userSavedText.setText("Usuario registrado exitosamente");
                    }
                }
                else
                {
                    errorText_password2.setText("Error: las contraseñas no coinciden");
                }
            }
            
        }
        catch (InvalidEmailException ex) 
        {
            errorText_email.setText(ex.getMessage());
        } 
        catch (EmptyEmailException ex) 
        {
            errorText_email.setText(ex.getMessage());
        } 
        catch (EmptyPasswordException ex) 
        {
            errorText_password.setText(ex.getMessage());
        } 
        catch (InvalidPasswordException ex) 
        {
            errorText_password.setText(ex.getMessage());
        } 
        catch (UserAlreadyExistException ex) 
        {
            errorText_signup.setText(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_ButtonSignupActionPerformed

    /**
     * text_emailActionPerformed
     * @param evt 
     */
    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_text_emailActionPerformed

    /**
     * changeSeePassword
     * @param passwordField
     * @param seePassword
     * @param button 
     */
    private void changeSeePassword(JPasswordField passwordField, boolean seePassword, JButton button)
    {
        if(seePassword)
        {
            //si esta configurado para ver la contraseña va a cambiar a no ver contraseña
            passwordField.setEchoChar('•');
            
            changeJButton(button, seePasswordButton.getDontSeePassword());
        }
        else
        {
            //si esta configurado para no ver la contraseña va a cambiar a ver contraseña
            passwordField.setEchoChar((char)0);
            
            changeJButton(button, seePasswordButton.getSeePassword());
        }
    }
    
    /**
     * buttonSeePasswordActionPerformed
     * @param evt 
     */
    private void buttonSeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeePasswordActionPerformed
        if(seePassword1)
        {
            seePassword1 = false;
        }
        else
        {
            seePassword1 = true;
        }
        changeSeePassword(text_password, seePassword1,buttonSeePassword);
    }//GEN-LAST:event_buttonSeePasswordActionPerformed

    /**
     * buttonSeePassword2ActionPerformed
     * @param evt 
     */
    private void buttonSeePassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeePassword2ActionPerformed
        // TODO add your handling code here:
        if(seePassword2)
        {
            seePassword2 = false;
        }
        else
        {
            seePassword2 = true;
        }
        changeSeePassword(text_passwordConfirmed, seePassword2,buttonSeePassword2);
    }//GEN-LAST:event_buttonSeePassword2ActionPerformed

    /**
     * changeJButton
     * @param boton
     * @param imagenBoton 
     */
    private void changeJButton(JButton boton, ButtonImage imagenBoton)
    {
        String icon = imagenBoton.getIcon();
        String pressedIcon = imagenBoton.getPressedIcon();
        String rolloverIcon = imagenBoton.getRolloverIcon();
        
        //cambio las caracteristicas del boton enviado por parametro
        boton.setIcon(new ImageIcon(getClass().getResource(icon)));
        boton.setPressedIcon(new ImageIcon(getClass().getResource(pressedIcon)));
        boton.setRolloverIcon(new ImageIcon(getClass().getResource(rolloverIcon)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSignup;
    private javax.swing.JButton buttonSeePassword;
    private javax.swing.JButton buttonSeePassword2;
    private javax.swing.JLabel errorText_email;
    private javax.swing.JLabel errorText_password;
    private javax.swing.JLabel errorText_password2;
    private javax.swing.JLabel errorText_signup;
    private javax.swing.JLabel imagenFondoContraseña;
    private javax.swing.JLabel imagenFondoContraseña2;
    private javax.swing.JLabel imagenFondoEmail;
    private javax.swing.JLabel infoUsuarioEmail;
    private javax.swing.JLabel infoUsuarioPassword;
    private javax.swing.JLabel infoUsuarioPassword2;
    private javax.swing.JTextField text_email;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JPasswordField text_passwordConfirmed;
    private javax.swing.JLabel userSavedText;
    // End of variables declaration//GEN-END:variables
}
