/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import java.util.logging.Level;
import java.util.logging.Logger;
import static paneles.PantallaInicial.sistemaUsuarios;
import user.User;
import user.exceptions.EmptyEmailException;
import user.exceptions.EmptyPasswordException;
import user.exceptions.InvalidEmailException;
import user.exceptions.InvalidPasswordException;
import user.exceptions.UserAlreadyExistException;

/**
 *
 * @author sofia
 */
public class SignupPanel extends javax.swing.JPanel {

    /**
     * Creates new form panelSignup
     */
    public SignupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_password = new javax.swing.JPasswordField();
        infoUsuarioEmail = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        imagenFondoEmail = new javax.swing.JLabel();
        infoUsuarioPassword = new javax.swing.JLabel();
        imagenFondoContraseña = new javax.swing.JLabel();
        ButtonSignup = new javax.swing.JButton();
        text_passwordConfirmed = new javax.swing.JPasswordField();
        imagenFondoContraseña2 = new javax.swing.JLabel();
        infoUsuarioPassword2 = new javax.swing.JLabel();
        errorText_email = new javax.swing.JLabel();
        errorText_password = new javax.swing.JLabel();
        errorText_password2 = new javax.swing.JLabel();
        errorText_signup = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 128, 97));
        setMaximumSize(new java.awt.Dimension(700, 307));
        setMinimumSize(new java.awt.Dimension(700, 307));
        setPreferredSize(new java.awt.Dimension(700, 307));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_password.setBackground(new java.awt.Color(195, 225, 203));
        text_password.setForeground(new java.awt.Color(102, 102, 102));
        text_password.setBorder(null);
        add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 350, 30));

        infoUsuarioEmail.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioEmail.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioEmail.setText("Email");
        add(infoUsuarioEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        text_email.setBackground(new java.awt.Color(195, 225, 203));
        text_email.setForeground(new java.awt.Color(102, 102, 102));
        text_email.setBorder(null);
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });
        add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 350, 30));

        imagenFondoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        infoUsuarioPassword.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioPassword.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword.setText("Contraseña");
        add(infoUsuarioPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        imagenFondoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        ButtonSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/Signup.png"))); // NOI18N
        ButtonSignup.setBorderPainted(false);
        ButtonSignup.setContentAreaFilled(false);
        ButtonSignup.setMaximumSize(new java.awt.Dimension(110, 40));
        ButtonSignup.setMinimumSize(new java.awt.Dimension(110, 40));
        ButtonSignup.setPreferredSize(new java.awt.Dimension(110, 40));
        ButtonSignup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/SignupMouseOver.png"))); // NOI18N
        ButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignupActionPerformed(evt);
            }
        });
        add(ButtonSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        text_passwordConfirmed.setBackground(new java.awt.Color(195, 225, 203));
        text_passwordConfirmed.setForeground(new java.awt.Color(102, 102, 102));
        text_passwordConfirmed.setBorder(null);
        add(text_passwordConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 350, 30));

        imagenFondoContraseña2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonesLogIn/barraTexto.png"))); // NOI18N
        add(imagenFondoContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        infoUsuarioPassword2.setBackground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        infoUsuarioPassword2.setForeground(new java.awt.Color(195, 225, 203));
        infoUsuarioPassword2.setText("Confirme su contraseña");
        add(infoUsuarioPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        errorText_email.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_email.setForeground(new java.awt.Color(255, 153, 153));
        errorText_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_email.setAutoscrolls(true);
        errorText_email.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 140, 20));

        errorText_password.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_password.setForeground(new java.awt.Color(255, 153, 153));
        errorText_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_password.setAutoscrolls(true);
        errorText_password.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 20));

        errorText_password2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_password2.setForeground(new java.awt.Color(255, 153, 153));
        errorText_password2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_password2.setAutoscrolls(true);
        errorText_password2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, 20));

        errorText_signup.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        errorText_signup.setForeground(new java.awt.Color(255, 153, 153));
        errorText_signup.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorText_signup.setAutoscrolls(true);
        errorText_signup.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(errorText_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 250, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignupActionPerformed
        //vacio los textos de error
        errorText_email.setText("");
        errorText_password.setText("");
        errorText_password2.setText("");
        errorText_signup.setText("");
        
        // Se inscribe un nuevo usuario
        //verificar que el mail es valido
        try
        {
            boolean validEmail = User.validEmail(text_email.getText());
            boolean validPassword = User.validPassword(text_password.getText());
            if(validEmail && validPassword)
            {
                //verifico antes que la segunda contraseña y la primera coincidan
                if(text_password.getText().contentEquals(text_passwordConfirmed.getText()))
                {
                    //creo un nuevo usuario
                    User user = new User(text_email.getText(),text_password.getText());
                    
                    //agrego el usuario a el sistema
                    sistemaUsuarios.signup(user);
                    
                    //guardo la lista de usuarios en el archivo
                    
                    //mensaje verde el usuario se guardo correctamente
                }
                else
                {
                    errorText_password2.setText("Error: las contraseñas no coinciden");
                }
            }
            
        }
        catch (InvalidEmailException ex) 
        {
            errorText_email.setText(ex.getMessage());
        } 
        catch (EmptyEmailException ex) 
        {
            errorText_email.setText(ex.getMessage());
        } 
        catch (EmptyPasswordException ex) 
        {
            errorText_password.setText(ex.getMessage());
        } 
        catch (InvalidPasswordException ex) 
        {
            errorText_password.setText(ex.getMessage());
        } 
        catch (UserAlreadyExistException ex) 
        {
            errorText_signup.setText(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_ButtonSignupActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_text_emailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSignup;
    private javax.swing.JLabel errorText_email;
    private javax.swing.JLabel errorText_password;
    private javax.swing.JLabel errorText_password2;
    private javax.swing.JLabel errorText_signup;
    private javax.swing.JLabel imagenFondoContraseña;
    private javax.swing.JLabel imagenFondoContraseña2;
    private javax.swing.JLabel imagenFondoEmail;
    private javax.swing.JLabel infoUsuarioEmail;
    private javax.swing.JLabel infoUsuarioPassword;
    private javax.swing.JLabel infoUsuarioPassword2;
    private javax.swing.JTextField text_email;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JPasswordField text_passwordConfirmed;
    // End of variables declaration//GEN-END:variables
}
