/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles.menu;


/**
 *
 * @author sofia
 */
public class MenuPanel extends javax.swing.JPanel 
{
    public static int option;//1 Ver usuario |2 Modificar contraseña |3 Modificar localizacion
                             //4 Eliminar usuario |5 Info sobre TaskMaster Pro

    /**
     * Creates new form menu
     */
    public MenuPanel() {
        initComponents();
        option = 0;//no hay ninguna opcion
    }
    
    public int getOpcion()
    {
        return option;
    }

    public void resetMenu()
    {
        option = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSeeUser = new javax.swing.JButton();
        ButtonModifyPassword = new javax.swing.JButton();
        ButtonModifyLocation = new javax.swing.JButton();
        ButtonDeleteUser = new javax.swing.JButton();
        ButtonInfoApp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(195, 225, 203));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonSeeUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ButtonSeeUser.setForeground(new java.awt.Color(203, 226, 191));
        ButtonSeeUser.setText("■  Ver usuario");
        ButtonSeeUser.setBorder(null);
        ButtonSeeUser.setBorderPainted(false);
        ButtonSeeUser.setContentAreaFilled(false);
        ButtonSeeUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonSeeUser.setMaximumSize(new java.awt.Dimension(182, 20));
        ButtonSeeUser.setMinimumSize(new java.awt.Dimension(182, 20));
        ButtonSeeUser.setPreferredSize(new java.awt.Dimension(182, 20));
        ButtonSeeUser.setRequestFocusEnabled(false);
        ButtonSeeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeeUserActionPerformed(evt);
            }
        });
        add(ButtonSeeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        ButtonModifyPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ButtonModifyPassword.setForeground(new java.awt.Color(203, 226, 191));
        ButtonModifyPassword.setText("■  Modificar contraseña");
        ButtonModifyPassword.setBorder(null);
        ButtonModifyPassword.setBorderPainted(false);
        ButtonModifyPassword.setContentAreaFilled(false);
        ButtonModifyPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonModifyPassword.setMaximumSize(new java.awt.Dimension(182, 20));
        ButtonModifyPassword.setMinimumSize(new java.awt.Dimension(182, 20));
        ButtonModifyPassword.setPreferredSize(new java.awt.Dimension(182, 20));
        ButtonModifyPassword.setRequestFocusEnabled(false);
        ButtonModifyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModifyPasswordActionPerformed(evt);
            }
        });
        add(ButtonModifyPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        ButtonModifyLocation.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ButtonModifyLocation.setForeground(new java.awt.Color(203, 226, 191));
        ButtonModifyLocation.setText("■  Modificar localizacion");
        ButtonModifyLocation.setBorder(null);
        ButtonModifyLocation.setBorderPainted(false);
        ButtonModifyLocation.setContentAreaFilled(false);
        ButtonModifyLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonModifyLocation.setMaximumSize(new java.awt.Dimension(182, 20));
        ButtonModifyLocation.setMinimumSize(new java.awt.Dimension(182, 20));
        ButtonModifyLocation.setPreferredSize(new java.awt.Dimension(182, 20));
        ButtonModifyLocation.setRequestFocusEnabled(false);
        ButtonModifyLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModifyLocationActionPerformed(evt);
            }
        });
        add(ButtonModifyLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        ButtonDeleteUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ButtonDeleteUser.setForeground(new java.awt.Color(203, 226, 191));
        ButtonDeleteUser.setText("■  Eliminar usuario");
        ButtonDeleteUser.setBorder(null);
        ButtonDeleteUser.setBorderPainted(false);
        ButtonDeleteUser.setContentAreaFilled(false);
        ButtonDeleteUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonDeleteUser.setMaximumSize(new java.awt.Dimension(182, 20));
        ButtonDeleteUser.setMinimumSize(new java.awt.Dimension(182, 20));
        ButtonDeleteUser.setPreferredSize(new java.awt.Dimension(182, 20));
        ButtonDeleteUser.setRequestFocusEnabled(false);
        ButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteUserActionPerformed(evt);
            }
        });
        add(ButtonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        ButtonInfoApp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ButtonInfoApp.setForeground(new java.awt.Color(203, 226, 191));
        ButtonInfoApp.setText("■  Info sobre TaskMaster Pro ");
        ButtonInfoApp.setBorder(null);
        ButtonInfoApp.setBorderPainted(false);
        ButtonInfoApp.setContentAreaFilled(false);
        ButtonInfoApp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonInfoApp.setMaximumSize(new java.awt.Dimension(182, 20));
        ButtonInfoApp.setMinimumSize(new java.awt.Dimension(182, 20));
        ButtonInfoApp.setPreferredSize(new java.awt.Dimension(182, 20));
        ButtonInfoApp.setRequestFocusEnabled(false);
        ButtonInfoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInfoAppActionPerformed(evt);
            }
        });
        add(ButtonInfoApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu/background.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(203, 162));
        jLabel1.setMinimumSize(new java.awt.Dimension(203, 162));
        jLabel1.setPreferredSize(new java.awt.Dimension(203, 162));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));
    }// </editor-fold>//GEN-END:initComponents

    
    private void ButtonSeeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeeUserActionPerformed
        option = 1;
    }//GEN-LAST:event_ButtonSeeUserActionPerformed

    private void ButtonModifyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModifyPasswordActionPerformed
        option = 2;
    }//GEN-LAST:event_ButtonModifyPasswordActionPerformed

    private void ButtonModifyLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModifyLocationActionPerformed
        option = 3;
    }//GEN-LAST:event_ButtonModifyLocationActionPerformed

    private void ButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteUserActionPerformed
        option = 4;
    }//GEN-LAST:event_ButtonDeleteUserActionPerformed

    private void ButtonInfoAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInfoAppActionPerformed
        option = 5;
    }//GEN-LAST:event_ButtonInfoAppActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDeleteUser;
    private javax.swing.JButton ButtonInfoApp;
    private javax.swing.JButton ButtonModifyLocation;
    private javax.swing.JButton ButtonModifyPassword;
    private javax.swing.JButton ButtonSeeUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
