/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles.weather;

/**
 * NoLocationWeatherPanel
 * @author sofia
 */
public class NoLocationWeatherPanel extends javax.swing.JPanel {

    /**
     * Creates new form noLocationWeather
     */
    public NoLocationWeatherPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noLocationImage = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(195, 225, 203));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noLocationImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clima/noLocation.png"))); // NOI18N
        noLocationImage.setMaximumSize(new java.awt.Dimension(660, 170));
        noLocationImage.setMinimumSize(new java.awt.Dimension(660, 170));
        noLocationImage.setPreferredSize(new java.awt.Dimension(660, 170));
        add(noLocationImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clima/weatherBackground.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(660, 170));
        background.setMinimumSize(new java.awt.Dimension(660, 170));
        background.setPreferredSize(new java.awt.Dimension(660, 170));
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel noLocationImage;
    // End of variables declaration//GEN-END:variables
}
