/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles.ListasPaneles;

/**
 *
 * @author sofia
 */
public class TaskListCalendarPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskListCalendar
     */
    public TaskListCalendarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_year = new javax.swing.JTextField();
        text_day = new javax.swing.JTextField();
        text_month = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        text_newList = new javax.swing.JTextField();
        infoNewList = new javax.swing.JLabel();
        titleTaskList = new javax.swing.JLabel();
        backGroundText = new javax.swing.JLabel();
        backgroundTaskList = new javax.swing.JLabel();

        setBackground(new java.awt.Color(195, 225, 203));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_year.setBackground(new java.awt.Color(195, 225, 203));
        text_year.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        text_year.setForeground(new java.awt.Color(102, 102, 102));
        text_year.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_year.setBorder(null);
        text_year.setOpaque(false);
        text_year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_yearKeyTyped(evt);
            }
        });
        add(text_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 30, 30));

        text_day.setBackground(new java.awt.Color(195, 225, 203));
        text_day.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        text_day.setForeground(new java.awt.Color(102, 102, 102));
        text_day.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_day.setBorder(null);
        text_day.setOpaque(false);
        text_day.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_dayKeyTyped(evt);
            }
        });
        add(text_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 30, 30));

        text_month.setBackground(new java.awt.Color(195, 225, 203));
        text_month.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        text_month.setForeground(new java.awt.Color(102, 102, 102));
        text_month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_month.setBorder(null);
        text_month.setOpaque(false);
        text_month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_monthKeyTyped(evt);
            }
        });
        add(text_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 30));

        jLabel1.setBackground(new java.awt.Color(195, 225, 203));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(195, 225, 203));
        jLabel1.setText("Dia");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));

        jLabel4.setBackground(new java.awt.Color(195, 225, 203));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(195, 225, 203));
        jLabel4.setText("Mes");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, 30));

        jLabel5.setBackground(new java.awt.Color(195, 225, 203));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(195, 225, 203));
        jLabel5.setText("Año");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 30));

        buttonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas/botonCrear.png"))); // NOI18N
        buttonCreate.setBorderPainted(false);
        buttonCreate.setContentAreaFilled(false);
        buttonCreate.setMaximumSize(new java.awt.Dimension(94, 30));
        buttonCreate.setMinimumSize(new java.awt.Dimension(94, 30));
        buttonCreate.setPreferredSize(new java.awt.Dimension(94, 30));
        buttonCreate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas/botonCrearMouseOver.png"))); // NOI18N
        add(buttonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        text_newList.setBackground(new java.awt.Color(195, 225, 203));
        text_newList.setForeground(new java.awt.Color(102, 102, 102));
        text_newList.setBorder(null);
        text_newList.setPreferredSize(new java.awt.Dimension(100, 30));
        add(text_newList, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 440, -1));

        infoNewList.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        infoNewList.setForeground(new java.awt.Color(195, 225, 203));
        infoNewList.setText("Crear nueva lista");
        add(infoNewList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 30));

        titleTaskList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas/tituloListaSimpleConFecha.png"))); // NOI18N
        add(titleTaskList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        backGroundText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas/espacioTextoList.png"))); // NOI18N
        add(backGroundText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        backgroundTaskList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listas/fondoListas.png"))); // NOI18N
        add(backgroundTaskList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void text_dayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_dayKeyTyped
        //valida que la tecla ingresada por teclado sea solo numero
        char validate = evt.getKeyChar();
        
        if(Character.isLetter(validate))
        {
            //borro la ultima letra ingresara
            evt.consume();
        }
    }//GEN-LAST:event_text_dayKeyTyped

    private void text_monthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_monthKeyTyped
        //valida que la tecla ingresada por teclado sea solo numero
        char validate = evt.getKeyChar();
        
        if(Character.isLetter(validate))
        {
            //borro la ultima letra ingresara
            evt.consume();
        }
    }//GEN-LAST:event_text_monthKeyTyped

    private void text_yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_yearKeyTyped
        //valida que la tecla ingresada por teclado sea solo numero
        char validate = evt.getKeyChar();
        
        if(Character.isLetter(validate))
        {
            //borro la ultima letra ingresara
            evt.consume();
        }
    }//GEN-LAST:event_text_yearKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGroundText;
    private javax.swing.JLabel backgroundTaskList;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JLabel infoNewList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField text_day;
    private javax.swing.JTextField text_month;
    private javax.swing.JTextField text_newList;
    private javax.swing.JTextField text_year;
    private javax.swing.JLabel titleTaskList;
    // End of variables declaration//GEN-END:variables
}
